### ISSUE TITLE
npm安装的ikun-ui有残缺

### ISSUE THREAD

**Issue by LibraHp** [LAINE001/ikun-ui#3]
如果是使用“npm i ikun-ui”他会提示404
但是如果换成“npm i ikunui”，可以安装，但是组件有残缺

**Comment by LAINE001** [comment]
https://www.npmjs.com/package/ikuiv

正确的地址是这里，安装应该这样：npm install ikuiv。文档不准确，哈哈哈

**Comment by LAINE001** [comment]
组件和文档也不会同步，我自己搞着玩的。后面有时间再一起同步🏀
